/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef, type JSX, useEffect, useState } from 'react'
import { useGLTF, useAnimations, useFBX, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { lerp } from 'three/src/math/MathUtils.js'

// Define explicit node/material types for useGLTF
type AvatarGLTFResult = {
  nodes: {
    Hips: THREE.Bone,
    Streamoji_Avatar: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton
    },
    EyeLeft: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    EyeRight: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    Streamoji_Head: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    Streamoji_Teeth: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
  },
  materials: {
    Streamoji_Avatar: THREE.Material,
    Streamoji_Eye: THREE.Material,
    Streamoji_Skin: THREE.Material,
    Streamoji_Teeth: THREE.Material
  }
}

export function Avatar(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  // Cast result as AvatarGLTFResult to inform TS about node/material structure
  const { nodes, materials } = useGLTF('models/Avatar.glb') as unknown as AvatarGLTFResult

  // Load animations from FBX files
  const walkingFBX = useFBX('/animations/Walking.fbx')
  const idleFBX = useFBX('/animations/Breathing Idle.fbx')

  // Clone animation clips and set their names for reactivity/type safety
  const walkingClip = walkingFBX.animations?.[0]?.clone()
  if (walkingClip) { walkingClip.name = 'Walking' }
  const idleClip = idleFBX.animations?.[0]?.clone()
  if (idleClip) { idleClip.name = 'Idle' }
  // Only pass defined clips
  const animationClips = [walkingClip, idleClip].filter(Boolean) as THREE.AnimationClip[]

  // Pass the clips to useAnimations, then manage which one to play by name
  const { actions } = useAnimations(animationClips, group)

  const [animation, setAnimation] = useState<'Walking' | 'Idle'>('Walking')

  useEffect(() => {
    if (actions && actions[animation]) {
      actions[animation]!.reset().fadeIn(0.3).play()
      return () => {
        actions[animation]?.fadeOut(0.3)
      }
    }
  }, [animation, actions])

  const scrollData = useScroll();
  const lastScroll = useRef(0)

  useFrame(() => {
    if (group.current) {
      const scrollDelta = scrollData.offset - lastScroll.current
      let rotation = 0;
    
      if (Math.abs(scrollDelta) > 0.0001) {
        setAnimation('Walking')
        rotation = scrollDelta > 0 ? 0 : Math.PI
      } else {
        setAnimation('Idle')
      }
      group.current.rotation.y = lerp(group.current.rotation.y, rotation, 0.1)
      lastScroll.current = scrollData.offset
    }   
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Streamoji_Avatar"
            geometry={nodes.Streamoji_Avatar.geometry}
            material={materials.Streamoji_Avatar}
            skeleton={nodes.Streamoji_Avatar.skeleton}
          />
        </group>
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          name="Streamoji_Head"
          geometry={nodes.Streamoji_Head.geometry}
          material={materials.Streamoji_Skin}
          skeleton={nodes.Streamoji_Head.skeleton}
          morphTargetDictionary={nodes.Streamoji_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Head.morphTargetInfluences}
        />
        <skinnedMesh
          name="Streamoji_Teeth"
          geometry={nodes.Streamoji_Teeth.geometry}
          material={materials.Streamoji_Teeth}
          skeleton={nodes.Streamoji_Teeth.skeleton}
          morphTargetDictionary={nodes.Streamoji_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/Avatar.glb')