/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Balloon.glb -o src/components/Balloon.jsx -r public
Balloon by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/d1gDDhM7pTf)
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import type { JSX } from "react";

// Types for GLTF result
type GLTFResult = {
  nodes: {
    Balloon007: THREE.Mesh & { geometry: THREE.BufferGeometry };
  };
  materials: {
    phong1SG: THREE.MeshStandardMaterial;
  };
};

type BalloonProps = JSX.IntrinsicElements["group"] & {
  color?: THREE.ColorRepresentation;
};

export function Balloon(props: BalloonProps) {
  const { color, ...groupProps } = props;
  const { nodes, materials } = useGLTF("/models/Balloon.glb") as unknown as GLTFResult;
  return (
    <group {...groupProps} dispose={null}>
      <mesh geometry={nodes.Balloon007.geometry}>
        <meshStandardMaterial {...materials.phong1SG} color={color ?? materials.phong1SG.color} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Balloon.glb");
