/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/BookCaseWide.glb -o src/components/BookCase.jsx -r public
Bookcase Wide by Kay Lousberg (https://market.pmnd.rs/model/bookcase-wide)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type { GLTF } from "three/examples/jsm/Addons.js";

// Types for GLTF result
type GLTFResult = GLTF & {
  nodes: {
    Cube033: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube033_2: THREE.Mesh;
    Cube033_3: THREE.Mesh;
    Cube033_4: THREE.Mesh;
    Cube033_5: THREE.Mesh;
    Cube033_6: THREE.Mesh;
    Cube033_7: THREE.Mesh;
    Cube033_8: THREE.Mesh;
  };
  materials: {
    ["BrownDark.049"]: THREE.Material;
    ["PurpleDark.003"]: THREE.Material;
    ["White.034"]: THREE.Material;
    ["Metal.080"]: THREE.Material;
    ["BlueDark.003"]: THREE.Material;
    ["GreenDark.007"]: THREE.Material;
    ["WoodDark.005"]: THREE.Material;
    ["StoneDark.001"]: THREE.Material;
    ["Black.030"]: THREE.Material;
  };
};

export function BookCase(props: JSX.IntrinsicElements["group"]) {
  // Fix: cast useGLTF result to unknown first to fix type error
  const { nodes, materials } = useGLTF("/models/BookCaseWide.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials["BrownDark.049"]} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials["PurpleDark.003"]} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials["White.034"]} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials["Metal.080"]} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials["BlueDark.003"]} />
        <mesh geometry={nodes.Cube033_5.geometry} material={materials["GreenDark.007"]} />
        <mesh geometry={nodes.Cube033_6.geometry} material={materials["WoodDark.005"]} />
        <mesh geometry={nodes.Cube033_7.geometry} material={materials["StoneDark.001"]} />
        <mesh geometry={nodes.Cube033_8.geometry} material={materials["Black.030"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/BookCaseWide.glb");
