/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Couch Small.glb -o src/components/CouchSmall.jsx -r public
Couch Small by Quaternius (https://poly.pizza/m/ZOPP3KzNIk)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type { GLTF } from "three/examples/jsm/Addons.js";

// Types for GLTF result
type GLTFResult = GLTF & {
  nodes: {
    Couch_Small1_1: THREE.Mesh;
    Couch_Small1_2: THREE.Mesh;
  };
  materials: {
    Couch_Blue: THREE.Material;
    Black: THREE.Material;
  };
};

export function CouchSmall(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/Couch Small.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Couch_Small1_1.geometry}
          material={materials.Couch_Blue}
        />
        <mesh
          geometry={nodes.Couch_Small1_2.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Couch Small.glb");
