/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Laptop.glb -o src/components/Laptop.jsx -r public
Laptop / MacBook Pro by Alex Safayan [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/27hcX_w47Jb)
*/

import { useGLTF } from "@react-three/drei";
import { type ThreeElements } from "@react-three/fiber";
import type { JSX } from "react";
import { Mesh, BufferGeometry, Material } from "three";

// Define the expected structure of nodes and materials
type LaptopGLTFResult = {
  nodes: {
    "LapTop_Cube002-Mesh": Mesh & { geometry: BufferGeometry };
    "LapTop_Cube002-Mesh_1": Mesh & { geometry: BufferGeometry };
    "LapTop_Cube002-Mesh_2": Mesh & { geometry: BufferGeometry };
    "LapTop_Cube002-Mesh_3": Mesh & { geometry: BufferGeometry };
  };
  materials: {
    DarkGray: Material;
    lighterGray: Material;
    Gray2: Material;
    Screen: Material;
  };
};

export function Laptop(props: ThreeElements["group"]): JSX.Element {
  const { nodes, materials } = useGLTF("/models/Laptop.glb") as unknown as LaptopGLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["LapTop_Cube002-Mesh"].geometry}
        material={materials.DarkGray}
      />
      <mesh
        geometry={nodes["LapTop_Cube002-Mesh_1"].geometry}
        material={materials.lighterGray}
      />
      <mesh
        geometry={nodes["LapTop_Cube002-Mesh_2"].geometry}
        material={materials.Gray2}
      />
      <mesh
        geometry={nodes["LapTop_Cube002-Mesh_3"].geometry}
        material={materials.Screen}
      />
    </group>
  );
}

useGLTF.preload("/models/Laptop.glb");
