/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Pigeon.gltf -o src/components/Pigeon.jsx -r public
Pigeon by Quaternius (https://poly.pizza/m/9NGlBTpDEr)
*/

import * as THREE from "three";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useEffect, useRef, useState, type JSX } from "react";
import type { ThreeElements } from "@react-three/fiber";

// Typed nodes/materials for the loaded glTF
type PigeonGLTFResult = {
  nodes: {
    Root: THREE.Bone,
    Cube000: THREE.SkinnedMesh & { geometry: THREE.BufferGeometry; skeleton: THREE.Skeleton },
    Cube000_1: THREE.SkinnedMesh & { geometry: THREE.BufferGeometry; skeleton: THREE.Skeleton },
    Cube000_2: THREE.SkinnedMesh & { geometry: THREE.BufferGeometry; skeleton: THREE.Skeleton },
    Cube000_3: THREE.SkinnedMesh & { geometry: THREE.BufferGeometry; skeleton: THREE.Skeleton },
  },
  materials: {
    Pigeon_Main: THREE.Material,
    Pigeon_Secondary: THREE.Material,
    Eye_White: THREE.Material,
    Eye_Black: THREE.Material,
  },
  animations: THREE.AnimationClip[]
};

export function Pigeon(props: ThreeElements["group"]): JSX.Element {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF("/models/Pigeon.gltf") as unknown as PigeonGLTFResult;

  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState<string>("Flying_Idle");
  useEffect(() => {
    if (actions && actions[animation]) {
      actions[animation]!.reset().fadeIn(0.5).play();
      return () => {
        if (actions && actions[animation]) {
          actions[animation]!.fadeOut(0.5);
        }
      };
    }
    return;
  }, [actions, animation]);

  return (
    <group
      {...props}
      dispose={null}
      ref={group}
      onPointerEnter={() => setAnimation("Yes")}
      onPointerLeave={() => setAnimation("Flying_Idle")}
    >
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Pigeon">
            <skinnedMesh
              name="Cube000"
              geometry={nodes.Cube000.geometry}
              material={materials.Pigeon_Main}
              skeleton={nodes.Cube000.skeleton}
            />
            <skinnedMesh
              name="Cube000_1"
              geometry={nodes.Cube000_1.geometry}
              material={materials.Pigeon_Secondary}
              skeleton={nodes.Cube000_1.skeleton}
            />
            <skinnedMesh
              name="Cube000_2"
              geometry={nodes.Cube000_2.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube000_2.skeleton}
            />
            <skinnedMesh
              name="Cube000_3"
              geometry={nodes.Cube000_3.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube000_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Pigeon.gltf");
