/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Star.gltf -o src/components/Star.jsx -r public
Star by Kay Lousberg (https://market.pmnd.rs/model/star)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import  { useRef, type JSX } from "react";
import type { ThreeElements } from "@react-three/fiber";

// Types for Star.gltf
type StarGLTFResult = {
  nodes: {
    star: THREE.Mesh & { geometry: THREE.BufferGeometry }
  },
  materials: {
    "Yellow.030": THREE.Material
  }
};

export function Star(props: ThreeElements["group"]): JSX.Element {
  const { nodes, materials } = useGLTF("/models/Star.gltf") as unknown as StarGLTFResult;
  const ref = useRef<THREE.Group>(null);

  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.y += 0.06;
    }
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.star.geometry}
        material={materials["Yellow.030"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Star.gltf");
